---
#
# Ansible managed
#
repository:
  description: Install and configure Envoy on your linux system.
  homepage: https://buluma.github.io/
  topics: cloud, database, development, monitoring, networking, packaging, system, web, ansible, molecule, tox, playbook, hacktoberfest
