---
image: "buluma/github-action-molecule:5.0.0"

variables:
  PY_COLORS: 1

molecule:
  stage: build
  allow_failure: true
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  parallel:
    matrix:
      - image: "gitlab-runner"
        tag: "amazonlinux"
      - image: "gitlab-runner"
        tag: "amazonlinux2022"
      - image: "gitlab-runner"
        tag: "fedora"
      - image: "gitlab-runner"
        tag: "oraclelinux"
      - image: "gitlab-runner"
        tag: "ubuntu"
      - image: "gitlab-runner"
        tag: "redhat"
      - image: "gitlab-runner"
        tag: "centos"
      - image: "gitlab-runner"
        tag: "rockylinux"
      - image: "gitlab-runner"
        tag: "alpine"
      - image: "gitlab-runner"
        tag: "opensuse"
      - image: "gitlab-runner"
        tag: "archlinux"
      - image: "gitlab-runner"
        tag: "debian"
      - image: "gitlab-runner"
        tag: "alpine"
      # - image: "enterpriselinux"
      #   tag: "8"
      # - image: "amazonlinux"
      #   tag: "latest"
      # - image: "fedora-systemd"
      #   tag: "35"
      # - image: "fedora-systemd"
      #   tag: "latest"
      # - image: "docker-ubuntu-systemd"
      #   tag: "latest"
      # - image: "docker-ubuntu-systemd"
      #   tag: "bionic"
      # - image: "docker-ubuntu-systemd"
      #   tag: "focal"
      # - image: "docker-ubuntu-systemd"
      #   tag: "jammy"
      # - image: "debian-systemd"
      #   tag: "latest"
      # - image: "debian-systemd"
      #   tag: "buster"
