---
image: "buluma/github-action-molecule:5.0.0"

variables:
  PY_COLORS: 1

molecule:
  tags:
    - ec2-af-south-1
  stage: build
  allow_failure: true
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
      - image: "enterpriselinux"
        tag: "8"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "amazonlinux"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "35"
      - image: "fedora-systemd"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "rawhide"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "docker-ubuntu-systemd"
        tag: "jammy"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian-systemd"
        tag: "buster"

galaxy:
  tags:
    - ec2-af-south-1
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} ${CI_PROJECT_NAMESPACE} ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG != null
