---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: buluma.bootstrap
    # - role: buluma.setuptools
    # - role: buluma.openssl
    # - role: buluma.ca_certificates
